INSERT INTO CMSC269001AW.H_ATTRIBUTES (ID, CODE, NAME) VALUES (4, 'english_foundation', 'English Foundation');
INSERT INTO CMSC269001AW.H_ATTRIBUTES (ID, CODE, NAME) VALUES (5, 'math_foundation', 'Math Foundation');
INSERT INTO CMSC269001AW.H_ATTRIBUTES (ID, CODE, NAME) VALUES (6, 'speech_foundation', 'Speech Foundation');
INSERT INTO CMSC269001AW.H_ATTRIBUTES (ID, CODE, NAME) VALUES (7, 'art_distribution', 'Art Distribution');
INSERT INTO CMSC269001AW.H_ATTRIBUTES (ID, CODE, NAME) VALUES (8, 'behavioral_distribution', 'Behavioral Distribution');
INSERT INTO CMSC269001AW.H_ATTRIBUTES (ID, CODE, NAME) VALUES (9, 'humanities_distribution', 'Humanities Distribution');
INSERT INTO CMSC269001AW.H_ATTRIBUTES (ID, CODE, NAME) VALUES (10, 'natural_science_lab_distribution', 'Natural Science with Lab Distribution');
INSERT INTO CMSC269001AW.H_ATTRIBUTES (ID, CODE, NAME) VALUES (11, 'natural_science_distribution', 'Natural Science Distribution');
INSERT INTO CMSC269001AW.H_ATTRIBUTES (ID, CODE, NAME) VALUES (12, 'major', 'Major Requirement');
INSERT INTO CMSC269001AW.H_ATTRIBUTES (ID, CODE, NAME) VALUES (13, 'electives', 'Electives');